import { RoleType } from "@prisma/client";

/**
 * Standard system permissions taxonomy
 */
export const PERMISSIONS = {
  // Records & Ledger
  RECORDS_VIEW: "records.view",
  RECORDS_CREATE: "records.create",
  RECORDS_EDIT: "records.edit",
  RECORDS_VOID: "records.void",

  // Income & Expenses
  INCOME_VIEW: "income.view",
  INCOME_CREATE: "income.create",
  EXPENSES_VIEW: "expenses.view",
  EXPENSES_CREATE: "expenses.create",

  // Payments
  PAYMENTS_VIEW: "payments.view",
  PAYMENTS_CREATE: "payments.create",
  PAYMENTS_VOID: "payments.void",

  // Receivables & Payables
  RECEIVABLES_VIEW: "receivables.view",
  PAYABLES_VIEW: "payables.view",

  // Accounting & Reconcile
  ACCOUNTING_RECONCILE: "accounting.reconcile",
  OPENING_BALANCE_MANAGE: "opening_balance.manage",

  // Customers & Suppliers
  CUSTOMERS_VIEW: "customers.view",
  CUSTOMERS_MANAGE: "customers.manage",
  SUPPLIERS_VIEW: "suppliers.view",
  SUPPLIERS_MANAGE: "suppliers.manage",

  // Notes
  NOTES_VIEW: "notes.view",
  NOTES_MANAGE: "notes.manage",

  // Import / Export
  IMPORTS_VIEW: "imports.view",
  IMPORTS_EXECUTE: "imports.execute",
  IMPORTS_OVERRIDE_DUPLICATE: "imports.override_duplicate",
  IMPORTS_POST_FINANCIAL: "imports.post_financial",
  IMPORTS_ROLLBACK: "imports.rollback",
  IMPORTS_MANAGE_TEMPLATES: "imports.manage_templates",
  EXPORTS_EXECUTE: "exports.execute",

  // Reports
  REPORTS_VIEW: "reports.view",
  REPORTS_BUILDER_VIEW: "reports.builder.view",
  REPORTS_BUILDER_CREATE: "reports.builder.create",
  REPORTS_BUILDER_EDIT: "reports.builder.edit",
  REPORTS_BUILDER_DELETE: "reports.builder.delete",
  REPORTS_BUILDER_SHARE: "reports.builder.share",
  REPORTS_BUILDER_EXPORT: "reports.builder.export",
  REPORTS_MANAGEMENT_VIEW: "reports.management.view",

  // Month-End Accounting
  MONTH_END_VIEW: "month_end.view",
  MONTH_END_CLOSE: "month_end.close",
  MONTH_END_REOPEN: "month_end.reopen",
  MONTH_END_LOCK: "month_end.lock",
  MONTH_END_UNLOCK: "month_end.unlock",

  // User Management
  USERS_VIEW: "users.view",
  USERS_MANAGE: "users.manage",

  // Settings & Audit
  SETTINGS_VIEW: "settings.view",
  SETTINGS_MANAGE: "settings.manage",
  AUDIT_VIEW: "audit.view",

  // AI Assistant
  AI_USE: "ai.use",

  // CRM, Follow-Ups & Promises
  FOLLOWUPS_VIEW: "followups.view",
  FOLLOWUPS_CREATE: "followups.create",
  FOLLOWUPS_EDIT: "followups.edit",
  FOLLOWUPS_COMPLETE: "followups.complete",
  FOLLOWUPS_ASSIGN: "followups.assign",
  FOLLOWUPS_VIEW_ALL: "followups.view_all",
  PROMISES_VIEW: "promises.view",
  PROMISES_MANAGE: "promises.manage",

  // Document Management & Vault (Phase 13)
  DOCUMENTS_VIEW: "documents.view",
  DOCUMENTS_UPLOAD: "documents.upload",
  DOCUMENTS_DOWNLOAD: "documents.download",
  DOCUMENTS_EDIT: "documents.edit_metadata",
  DOCUMENTS_ARCHIVE: "documents.archive",
  DOCUMENTS_DELETE: "documents.delete",
  DOCUMENTS_RESTORE: "documents.restore",
  DOCUMENTS_VIEW_SENSITIVE: "documents.view_sensitive",
  DOCUMENTS_MANAGE_CATEGORIES: "documents.manage_categories",
  DOCUMENTS_MANAGE_RETENTION: "documents.manage_retention",

  // Audit Control Center & Security (Phase 15)
  AUDIT_VIEW_SENSITIVE: "audit.view_sensitive",
  AUDIT_EXPORT: "audit.export",
  AUDIT_VERIFY_INTEGRITY: "audit.verify_integrity",

  // Backup & Restore Architecture (Phase 15)
  BACKUPS_VIEW: "backups.view",
  BACKUPS_CREATE: "backups.create",
  BACKUPS_VERIFY: "backups.verify",
  BACKUPS_RESTORE_TEST: "backups.restore_test",
  BACKUPS_RESTORE_PRODUCTION: "backups.restore_production",
  BACKUPS_MANAGE_RETENTION: "backups.manage_retention",

  // System & Disaster Recovery (Phase 15)
  SYSTEM_MAINTENANCE_MODE: "system.maintenance_mode",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * Role Template Definitions
 */
export const ROLE_PERMISSION_TEMPLATES: Record<RoleType, PermissionCode[]> = {
  OWNER: Object.values(PERMISSIONS), // All permissions
  ADMIN: [
    PERMISSIONS.RECORDS_VIEW,
    PERMISSIONS.RECORDS_CREATE,
    PERMISSIONS.RECORDS_EDIT,
    PERMISSIONS.RECORDS_VOID,
    PERMISSIONS.INCOME_VIEW,
    PERMISSIONS.INCOME_CREATE,
    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_CREATE,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.PAYMENTS_VOID,
    PERMISSIONS.RECEIVABLES_VIEW,
    PERMISSIONS.PAYABLES_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_MANAGE,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.SUPPLIERS_MANAGE,
    PERMISSIONS.NOTES_VIEW,
    PERMISSIONS.NOTES_MANAGE,
    PERMISSIONS.IMPORTS_VIEW,
    PERMISSIONS.IMPORTS_EXECUTE,
    PERMISSIONS.IMPORTS_OVERRIDE_DUPLICATE,
    PERMISSIONS.IMPORTS_POST_FINANCIAL,
    PERMISSIONS.IMPORTS_ROLLBACK,
    PERMISSIONS.IMPORTS_MANAGE_TEMPLATES,
    PERMISSIONS.EXPORTS_EXECUTE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.MONTH_END_VIEW,
    PERMISSIONS.MONTH_END_CLOSE,
    PERMISSIONS.MONTH_END_REOPEN,
    PERMISSIONS.MONTH_END_LOCK,
    PERMISSIONS.MONTH_END_UNLOCK,
    PERMISSIONS.ACCOUNTING_RECONCILE,
    PERMISSIONS.OPENING_BALANCE_MANAGE,
    PERMISSIONS.AI_USE,
    PERMISSIONS.FOLLOWUPS_VIEW,
    PERMISSIONS.FOLLOWUPS_CREATE,
    PERMISSIONS.FOLLOWUPS_EDIT,
    PERMISSIONS.FOLLOWUPS_COMPLETE,
    PERMISSIONS.FOLLOWUPS_ASSIGN,
    PERMISSIONS.FOLLOWUPS_VIEW_ALL,
    PERMISSIONS.PROMISES_VIEW,
    PERMISSIONS.PROMISES_MANAGE,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_UPLOAD,
    PERMISSIONS.DOCUMENTS_DOWNLOAD,
    PERMISSIONS.DOCUMENTS_EDIT,
    PERMISSIONS.DOCUMENTS_ARCHIVE,
    PERMISSIONS.DOCUMENTS_DELETE,
    PERMISSIONS.DOCUMENTS_RESTORE,
    PERMISSIONS.DOCUMENTS_VIEW_SENSITIVE,
    PERMISSIONS.DOCUMENTS_MANAGE_CATEGORIES,
    PERMISSIONS.DOCUMENTS_MANAGE_RETENTION,
    PERMISSIONS.REPORTS_BUILDER_VIEW,
    PERMISSIONS.REPORTS_BUILDER_CREATE,
    PERMISSIONS.REPORTS_BUILDER_EDIT,
    PERMISSIONS.REPORTS_BUILDER_DELETE,
    PERMISSIONS.REPORTS_BUILDER_SHARE,
    PERMISSIONS.REPORTS_BUILDER_EXPORT,
    PERMISSIONS.REPORTS_MANAGEMENT_VIEW,
    PERMISSIONS.AUDIT_VIEW_SENSITIVE,
    PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.AUDIT_VERIFY_INTEGRITY,
    PERMISSIONS.BACKUPS_VIEW,
    PERMISSIONS.BACKUPS_CREATE,
    PERMISSIONS.BACKUPS_VERIFY,
    PERMISSIONS.BACKUPS_RESTORE_TEST,
    PERMISSIONS.BACKUPS_MANAGE_RETENTION,
    PERMISSIONS.SYSTEM_MAINTENANCE_MODE,
  ],
  ACCOUNTANT: [
    PERMISSIONS.RECORDS_VIEW,
    PERMISSIONS.RECORDS_CREATE,
    PERMISSIONS.RECORDS_EDIT,
    PERMISSIONS.RECORDS_VOID,
    PERMISSIONS.INCOME_VIEW,
    PERMISSIONS.INCOME_CREATE,
    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_CREATE,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.PAYMENTS_VOID,
    PERMISSIONS.RECEIVABLES_VIEW,
    PERMISSIONS.PAYABLES_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_MANAGE,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.SUPPLIERS_MANAGE,
    PERMISSIONS.NOTES_VIEW,
    PERMISSIONS.NOTES_MANAGE,
    PERMISSIONS.IMPORTS_VIEW,
    PERMISSIONS.IMPORTS_EXECUTE,
    PERMISSIONS.IMPORTS_OVERRIDE_DUPLICATE,
    PERMISSIONS.IMPORTS_POST_FINANCIAL,
    PERMISSIONS.IMPORTS_ROLLBACK,
    PERMISSIONS.IMPORTS_MANAGE_TEMPLATES,
    PERMISSIONS.EXPORTS_EXECUTE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.MONTH_END_VIEW,
    PERMISSIONS.MONTH_END_CLOSE,
    PERMISSIONS.MONTH_END_REOPEN,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.ACCOUNTING_RECONCILE,
    PERMISSIONS.OPENING_BALANCE_MANAGE,
    PERMISSIONS.AI_USE,
    PERMISSIONS.FOLLOWUPS_VIEW,
    PERMISSIONS.FOLLOWUPS_CREATE,
    PERMISSIONS.FOLLOWUPS_EDIT,
    PERMISSIONS.FOLLOWUPS_COMPLETE,
    PERMISSIONS.FOLLOWUPS_VIEW_ALL,
    PERMISSIONS.PROMISES_VIEW,
    PERMISSIONS.PROMISES_MANAGE,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_UPLOAD,
    PERMISSIONS.DOCUMENTS_DOWNLOAD,
    PERMISSIONS.DOCUMENTS_EDIT,
    PERMISSIONS.DOCUMENTS_ARCHIVE,
    PERMISSIONS.DOCUMENTS_RESTORE,
    PERMISSIONS.DOCUMENTS_VIEW_SENSITIVE,
    PERMISSIONS.DOCUMENTS_MANAGE_CATEGORIES,
    PERMISSIONS.REPORTS_BUILDER_VIEW,
    PERMISSIONS.REPORTS_BUILDER_CREATE,
    PERMISSIONS.REPORTS_BUILDER_EDIT,
    PERMISSIONS.REPORTS_BUILDER_SHARE,
    PERMISSIONS.REPORTS_BUILDER_EXPORT,
    PERMISSIONS.REPORTS_MANAGEMENT_VIEW,
  ],
  STAFF: [
    PERMISSIONS.RECORDS_VIEW,
    PERMISSIONS.RECORDS_CREATE,
    PERMISSIONS.INCOME_VIEW,
    PERMISSIONS.INCOME_CREATE,
    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_CREATE,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.RECEIVABLES_VIEW,
    PERMISSIONS.PAYABLES_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_MANAGE,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.NOTES_VIEW,
    PERMISSIONS.NOTES_MANAGE,
    PERMISSIONS.MONTH_END_VIEW,
    PERMISSIONS.FOLLOWUPS_VIEW,
    PERMISSIONS.FOLLOWUPS_CREATE,
    PERMISSIONS.FOLLOWUPS_EDIT,
    PERMISSIONS.FOLLOWUPS_COMPLETE,
    PERMISSIONS.PROMISES_VIEW,
    PERMISSIONS.PROMISES_MANAGE,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_UPLOAD,
    PERMISSIONS.DOCUMENTS_DOWNLOAD,
    PERMISSIONS.DOCUMENTS_EDIT,
    PERMISSIONS.REPORTS_BUILDER_VIEW,
    PERMISSIONS.REPORTS_BUILDER_EXPORT,
  ],
  VIEWER: [
    PERMISSIONS.RECORDS_VIEW,
    PERMISSIONS.INCOME_VIEW,
    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.RECEIVABLES_VIEW,
    PERMISSIONS.PAYABLES_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.SUPPLIERS_VIEW,
    PERMISSIONS.NOTES_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.MONTH_END_VIEW,
    PERMISSIONS.FOLLOWUPS_VIEW,
    PERMISSIONS.PROMISES_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_DOWNLOAD,
    PERMISSIONS.REPORTS_BUILDER_VIEW,
  ],
};

/**
 * Check if a user possesses a specific permission code.
 * OWNER role always evaluates to true.
 */
export function hasPermission(
  userPermissions: string[],
  userRoles: RoleType[] | string[],
  requiredPermission: string
): boolean {
  if (userRoles.includes("OWNER") || userRoles.includes(RoleType.OWNER)) {
    return true;
  }
  return userPermissions.includes(requiredPermission) || userPermissions.includes("*");
}
